spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  cache:
    type: redis
  data:
    mongodb:
      uri: mongodb+srv://admin:admin@cluster0.edjo3.mongodb.net/
      database: opendata
    redis:
      host: redis-18096.c1.us-central1-2.gce.redns.redis-cloud.com
      port: 18096
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}
      timeout: 6000ms



jwt:
  issuer: project.doctalk@gmail.com
  secret: "jfsgkhdsjkweoiruwqejkrfbhnsadkjlfghbwerqewrsdfgdsfagbdf"
  access-expiration: 3600
  refresh-expiration: 8640

server:
  port: 8080
  address: 0.0.0.0
  max-http-header-size: 16KB
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 1024 # 1KB ??? ??? ?? ??


logging:
  level:
    root: INFO
    org.springframework.security: DEBUG

api_secret: 65727076703838343130386d59744e75
